# Generated by Django 5.2.5 on 2025-08-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_alter_product_category_productsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsImage',
        ),
    ]
