# Generated by Django 5.2.5 on 2025-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0003_delete_productsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('shoes', 'shoes'), ('accessories', 'accessories'), ('jewelry', 'jewelry'), ('watches', 'watches')], max_length=255),
        ),
    ]
