# Generated by Django 5.2.5 on 2025-08-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0005_favoriteitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitems',
            name='thumbnail',
        ),
    ]
