# Generated by Django 5.2.5 on 2025-08-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_favoriteitems_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitems',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_store.product', unique=True),
        ),
    ]
