# Generated by Django 5.2.5 on 2025-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0008_alter_favoriteitems_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitems',
            name='product_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
