# Generated by Django 5.2.5 on 2025-08-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0009_alter_favoriteitems_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitems',
            name='product_id',
        ),
    ]
