# Generated by Django 5.2.5 on 2025-08-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0013_product_isfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isFavorite',
        ),
        migrations.AlterField(
            model_name='favoriteitems',
            name='product_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_store.product'),
        ),
    ]
