# Generated by Django 5.2.5 on 2025-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0014_remove_product_isfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
