# Generated by Django 5.2.5 on 2025-08-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0015_product_isfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isFavorite',
        ),
    ]
