# Generated by Django 5.2.5 on 2025-08-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
