# Generated by Django 5.2.5 on 2025-08-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0018_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
