# Generated by Django 5.2.5 on 2025-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0019_remove_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
