# Generated by Django 5.2.5 on 2025-08-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0020_cart_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size',
            new_name='footwear_size',
        ),
        migrations.AddField(
            model_name='cart',
            name='clothing_size',
            field=models.CharField(default='null', max_length=10, null=True),
        ),
    ]
