# Generated by Django 5.2.5 on 2025-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0021_rename_size_cart_footwear_size_cart_clothing_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='old_price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
