# Generated by Django 5.2.5 on 2025-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0022_remove_cart_old_price_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
