# Generated by Django 5.2.5 on 2025-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0023_cart_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='clothing_size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='footwear_size',
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
