# Generated by Django 5.2.5 on 2025-08-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0024_remove_cart_clothing_size_remove_cart_footwear_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_checkout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
