# Generated by Django 5.2.5 on 2025-08-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0025_cart_total_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_checkout',
        ),
    ]
