# Generated by Django 5.2.5 on 2025-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0026_remove_cart_total_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
